{
    'name': 'Money Lending',
    'version': '1.0.0',
    'category': 'Finance',
    'author': 'Cris-aian Vergara',
    'sequence': -100,
    'summary': 'Money lending',
    'description': """Money lending""",
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/money_lending_menus.xml',
        'views/borrower_views.xml',
        'views/borrow_money_views.xml',
        'views/occupation_views.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}